---
- name: ansbile handler
  hosts: webservers
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      update_cache: yes
      state: latest
    notify: restart httpd
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted